name: Build APK
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Unzip
        run: |
          ls -la
          unzip -o "*.zip"
          rm -f *.zip
          ls -la
          if [ -f "Mera Ai Aap-Source code/gradlew" ]; then mv "Mera Ai Aap-Source code"/*. && mv "Mera Ai Aap-Source code"/.*. 2>/dev/null || true; fi
          F=$(find. -name gradlew -type f | head -n 1); echo "found $F"; D=$(dirname "$F"); if [ "$D"!= "." ]; then cp -r $D/*. 2>/dev/null || true; cp -r $D/.*. 2>/dev/null || true; fi
          ls -la
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '17'
      - name: Setup Android
        uses: android-actions/setup-android@v3
      - name: Build
        run: chmod +x gradlew &&./gradlew assembleDebug
      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: app/build/outputs/apk/debug/*.apk
